### ISSUE TITLE
_dataset: Put a spinner when downloading data until the file is ready to be put in the drive. 

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#85]
When click on download a dataset, there could be a very long lag before the window to save teh file props up This could be disconcerting and the page needs to offer a spinner  and disable page until the other bit comes up/ 

Solution: once the button is clilcked, set a spinner modal to visible. When the event of the file updoad thing is on, then set the modal to not visible. 

```css
.myModal {

  position: fixed; /* Stay in place */

  z-index: 1; /* Sit on top */

  left: 0;

  top: 0;

  width: 100%; /* Full width */

  height: 100%; /* Full height */

  overflow: auto; /* Enable scroll if needed */

  background-color: rgb(0,0,0); /* Fallback color */

  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */

}



.myModal .centered{

  margin: 0;

  position: absolute;

  top: 50%;

  left: 50%;

  transform: translate(-50%, -50%);

}

[11:41] Alberto Stella
.loader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #fed316;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
  
}

/* Safari */
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}


```
```html

<div class="container-fluid myModal" *ngIf="loading">

  <div class="row centered">

    <div class="row justify-content-center">

      <div class="loader "></div>

    </div>

    <div class="row">

      <div class="text-center">

        <p style="font-weight: bold; color: white;">Loading...</p>

      </div>

    </div>

  </div>

</div>
```
